### ISSUE TITLE
Lising token - VDC

### ISSUE THREAD

**Issue by vid-stream** [forkdelta/tokenbase#284]
Contract address: 0xcc2ae7ad8f32ea3bd38d0192d20e465503ae698d

Issuer's official website: https://vid-stream.org

Official contract address confirmation (MUST be linked from official website): https://vid-stream.org

A link to a third-party review or discussion of the token, like an established ICO review blog:
https://bitcointalk.org/index.php?topic=2095192.0 ] we mostly make use of telegram though https://t.me/joinchat/FJllmkQC6lu6_1nbuCz6Xw

Description:
Vid-stream is a video streaming platform where you get rewarded by the community for creating video content , as we all know that most users choice not to make use of youtube because of the so much rules they attached . Vid-stream rules will be based on the consensus of the community thanks.

**Comment by Kryptoniq** [comment]
0xcc2ae7ad8f32ea3bd38d0192d20e465503ae698d, https://vid-stream.org/

**Comment by freeatnet** [comment]
Unaddressed questions here https://bitcointalk.org/index.php?topic=2095192.msg29194477#msg29194477

**Comment by vid-stream** [comment]
this issue was addressed in the next post by my team, it was someone trying to create FUD in other to spoil this project but all has been resolved  https://bitcointalk.org/index.php?topic=2095192.msg29474906#msg29474906 ,  please read post after that and you will see that it has been addressed

**Comment by freeatnet** [comment]
@vid-stream Where it stands now is that a user has pointed out your team page listed at least one team team member whose photo was lifted off another website. In response, you have hid your team page and posted "not scam" message on BitcoinTalk. In my opinion, that does not resolve the issue. The only way to resolve this issue for you is to prepare a real team page with verifiable identities.

**Comment by vid-stream** [comment]
Alright

**Comment by vid-stream** [comment]
Team has been added to website https://vid-stream.org  , i hope we get listed 
the vid-stream community on telegram (https://t.me/joinchat/FJllmkQC6lu6_1nbuCz6Xw) will be happy for that.

**Comment by freeatnet** [comment]
"Angela Barth" became "Angel Barth", and yet…
> Angel Barth ANALYST
> Angel has Managed up to $55 million market-neutral REIT equity portfolio, using fundamental, economic, sector, and technical analysis tools to generate favorable risk-adjusted returns for over ten years.

> Portfolio Manager / Analyst / Trader
> Managed up to $55 million market-neutral REIT equity portfolio, using fundamental, economic, sector, and technical analysis tools to generate favorable risk-adjusted returns for ten years.

— "Portfolio Manager: Resume Samples", http://www.jobhero.com/resume-samples/portfolio-manager

"Molly Spencer" became "Martins Spencer", and yet…
> Martins Spencer PR OFFICER
> Martins has a 4 years exprience in public communications. Diverse experience in marketing, from event management to marketing strategy development, with a focus on infrastructure companies.

> Specialist with 10+ years of experience. Diverse experience in marketing, from event management to marketing strategy development, with a focus on infrastructure companies.

— https://london.keynote.ae/speaker/daria-generalova/

Additionally, other two team members' appearances have changed [quite drastically.](https://web.archive.org/web/20171002094140/https://vid-stream.org)
